### ISSUE TITLE
Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by queejie** [slavede/ngx-paginate#16]
Thanks for this module!

I'm unable to include it in my project, which is using Angular 7 and Typescript 3.2.4.
`ERROR in node_modules/ngx-paginate/ngx-paginate.d.ts.ɵa.html(2,9): : Object is possibly 'undefined'.`

**Comment by slavede** [comment]
How are you trying to import it?

**Comment by slavede** [comment]
Closing for being unresponsive and unable to reproduce
